#!/usr/bin/env node

var fs = require('fs'),
    argv = require('optimist').default('p', 0).argv,
    util  = require('util'),
    spawn = require('child_process').spawn,
    request = require('request');
    
    
function lookup_couchdb_pid() {
  return fs.readFileSync('/opt/couchbase/var/run/couchdb/couchdb.pid', 'utf8');
}


var pid = argv.p;
if(pid === 0) { 
  pid = lookup_couchdb_pid();
}
console.log('pid is ' + pid);
    
var ps = spawn('ps', ['-p', pid, '-o', 'pcpu=']);

ps.stdout.on('data', function (data) {
  var dataString = '' + data;
  console.log('cpu load: "' + dataString.trim() + '"');
  //now see how many changes listeners are running
  request({url:'http://localhost:5984/_stats', json:true}, function (error, response, body) {
    console.log('current changes listener count: ' + body.httpd.clients_requesting_changes.current);
  });
});

