#!/usr/bin/env node

var argv = require('optimist').argv,
    request = require('request');

var url = argv['_'][0],
    concurrency = argv['c'];

for (var i=0; i < concurrency; i++) {
    request(url, function(err, resp) {
        console.log(resp.body)
    })
};